"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .commercemoneyresponse import CommerceMoneyResponse, CommerceMoneyResponseTypedDict
from .commercepayerresponse import CommercePayerResponse, CommercePayerResponseTypedDict
from .commercepaymentmethodresponse import (
    CommercePaymentMethodResponse,
    CommercePaymentMethodResponseTypedDict,
)
from clerk_backend_api.types import BaseModel, Nullable, UNSET_SENTINEL
from enum import Enum
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class BillingPaymentAttemptObject(str, Enum):
    r"""String representing the object's type. Objects of the same type share the same value."""

    COMMERCE_PAYMENT = "commerce_payment"


class PayeeTypedDict(TypedDict):
    r"""The payee associated with this payment attempt."""


class Payee(BaseModel):
    r"""The payee associated with this payment attempt."""


class SubscriptionItemTypedDict(TypedDict):
    r"""The subscription item associated with this payment attempt."""


class SubscriptionItem(BaseModel):
    r"""The subscription item associated with this payment attempt."""


class BillingPaymentAttemptStatus(str, Enum):
    r"""The current status of the payment attempt."""

    PENDING = "pending"
    PAID = "paid"
    FAILED = "failed"


class BillingPaymentAttemptTypedDict(TypedDict):
    object: BillingPaymentAttemptObject
    r"""String representing the object's type. Objects of the same type share the same value."""
    id: str
    r"""Unique identifier for the payment attempt."""
    payment_id: str
    r"""Unique identifier for the associated payment."""
    instance_id: str
    r"""The ID of the instance this payment attempt belongs to."""
    charge_type: str
    r"""Type of charge for this payment attempt."""
    payee_id: str
    r"""Unique identifier for the payee."""
    payee: PayeeTypedDict
    r"""The payee associated with this payment attempt."""
    payer_id: str
    r"""Unique identifier for the payer."""
    payer: CommercePayerResponseTypedDict
    amount: CommerceMoneyResponseTypedDict
    payment_method_id: str
    r"""Unique identifier for the payment method."""
    payment_method: CommercePaymentMethodResponseTypedDict
    statement_id: str
    r"""Unique identifier for the associated statement."""
    gateway_external_id: Nullable[str]
    r"""External identifier from the payment gateway."""
    gateway_external_url: Nullable[str]
    r"""External URL from the payment gateway."""
    status: BillingPaymentAttemptStatus
    r"""The current status of the payment attempt."""
    paid_at: Nullable[int]
    r"""Unix timestamp (in milliseconds) when the payment was completed."""
    failed_at: Nullable[int]
    r"""Unix timestamp (in milliseconds) when the payment failed to be processed."""
    created_at: int
    r"""Unix timestamp (in milliseconds) when the payment attempt was created."""
    updated_at: int
    r"""Unix timestamp (in milliseconds) when the payment attempt was last updated."""
    subscription_item_id: NotRequired[str]
    r"""Unique identifier for the associated subscription item."""
    subscription_item: NotRequired[SubscriptionItemTypedDict]
    r"""The subscription item associated with this payment attempt."""


class BillingPaymentAttempt(BaseModel):
    object: BillingPaymentAttemptObject
    r"""String representing the object's type. Objects of the same type share the same value."""

    id: str
    r"""Unique identifier for the payment attempt."""

    payment_id: str
    r"""Unique identifier for the associated payment."""

    instance_id: str
    r"""The ID of the instance this payment attempt belongs to."""

    charge_type: str
    r"""Type of charge for this payment attempt."""

    payee_id: str
    r"""Unique identifier for the payee."""

    payee: Payee
    r"""The payee associated with this payment attempt."""

    payer_id: str
    r"""Unique identifier for the payer."""

    payer: CommercePayerResponse

    amount: CommerceMoneyResponse

    payment_method_id: str
    r"""Unique identifier for the payment method."""

    payment_method: CommercePaymentMethodResponse

    statement_id: str
    r"""Unique identifier for the associated statement."""

    gateway_external_id: Nullable[str]
    r"""External identifier from the payment gateway."""

    gateway_external_url: Nullable[str]
    r"""External URL from the payment gateway."""

    status: BillingPaymentAttemptStatus
    r"""The current status of the payment attempt."""

    paid_at: Nullable[int]
    r"""Unix timestamp (in milliseconds) when the payment was completed."""

    failed_at: Nullable[int]
    r"""Unix timestamp (in milliseconds) when the payment failed to be processed."""

    created_at: int
    r"""Unix timestamp (in milliseconds) when the payment attempt was created."""

    updated_at: int
    r"""Unix timestamp (in milliseconds) when the payment attempt was last updated."""

    subscription_item_id: Optional[str] = None
    r"""Unique identifier for the associated subscription item."""

    subscription_item: Optional[SubscriptionItem] = None
    r"""The subscription item associated with this payment attempt."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["subscription_item_id", "subscription_item"]
        nullable_fields = [
            "gateway_external_id",
            "gateway_external_url",
            "paid_at",
            "failed_at",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
