"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .commerceplanunitpricetier import (
    CommercePlanUnitPriceTier,
    CommercePlanUnitPriceTierTypedDict,
)
from clerk_backend_api.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class CommercePlanUnitPriceTypedDict(TypedDict):
    name: str
    r"""Name of the billable unit (for example, seats)"""
    block_size: int
    r"""Number of units included in each pricing block"""
    tiers: List[CommercePlanUnitPriceTierTypedDict]
    r"""Tiered pricing configuration for this unit"""


class CommercePlanUnitPrice(BaseModel):
    name: str
    r"""Name of the billable unit (for example, seats)"""

    block_size: int
    r"""Number of units included in each pricing block"""

    tiers: List[CommercePlanUnitPriceTier]
    r"""Tiered pricing configuration for this unit"""
