"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clerk_backend_api.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class CreateEmailAddressRequestBodyTypedDict(TypedDict):
    user_id: str
    r"""The ID representing the user"""
    email_address: str
    r"""The new email address. Must adhere to the RFC 5322 specification for email address format."""
    verified: NotRequired[Nullable[bool]]
    r"""When created, the email address will be marked as verified."""
    primary: NotRequired[Nullable[bool]]
    r"""Create this email address as the primary email address for the user.
    Default: false, unless it is the first email address.
    """


class CreateEmailAddressRequestBody(BaseModel):
    user_id: str
    r"""The ID representing the user"""

    email_address: str
    r"""The new email address. Must adhere to the RFC 5322 specification for email address format."""

    verified: OptionalNullable[bool] = UNSET
    r"""When created, the email address will be marked as verified."""

    primary: OptionalNullable[bool] = UNSET
    r"""Create this email address as the primary email address for the user.
    Default: false, unless it is the first email address.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["verified", "primary"])
        nullable_fields = set(["verified", "primary"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
