"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clerk_backend_api.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class CreateSignInTokenRequestBodyTypedDict(TypedDict):
    user_id: str
    r"""The ID of the user that can use the newly created sign in token"""
    org_id: NotRequired[Nullable[str]]
    r"""The ID of the organization to activate when the user signs in.
    Organizations must be enabled for the instance, and the user must be a member of the organization.
    """
    expires_in_seconds: NotRequired[Nullable[int]]
    r"""Optional parameter to specify the life duration of the sign in token in seconds.
    By default, the duration is 30 days.
    """


class CreateSignInTokenRequestBody(BaseModel):
    user_id: str
    r"""The ID of the user that can use the newly created sign in token"""

    org_id: OptionalNullable[str] = UNSET
    r"""The ID of the organization to activate when the user signs in.
    Organizations must be enabled for the instance, and the user must be a member of the organization.
    """

    expires_in_seconds: OptionalNullable[int] = 2592000
    r"""Optional parameter to specify the life duration of the sign in token in seconds.
    By default, the duration is 30 days.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["org_id", "expires_in_seconds"])
        nullable_fields = set(["org_id", "expires_in_seconds"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
