"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clerk_backend_api.types import BaseModel
from typing_extensions import TypedDict


class CreateSessionRequestBodyTypedDict(TypedDict):
    user_id: str
    r"""The ID representing the user"""


class CreateSessionRequestBody(BaseModel):
    user_id: str
    r"""The ID representing the user"""
