"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clerk_backend_api.types import BaseModel, UNSET_SENTINEL
from clerk_backend_api.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateMachineScopeRequestBodyTypedDict(TypedDict):
    to_machine_id: str
    r"""The ID of the machine that will be scoped to the current machine"""


class CreateMachineScopeRequestBody(BaseModel):
    to_machine_id: str
    r"""The ID of the machine that will be scoped to the current machine"""


class CreateMachineScopeRequestTypedDict(TypedDict):
    machine_id: str
    r"""The ID of the machine that will have access to another machine"""
    request_body: NotRequired[CreateMachineScopeRequestBodyTypedDict]


class CreateMachineScopeRequest(BaseModel):
    machine_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the machine that will have access to another machine"""

    request_body: Annotated[
        Optional[CreateMachineScopeRequestBody],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["RequestBody"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
