"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clerk_backend_api.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class DeletedObjectTypedDict(TypedDict):
    r"""Deleted Object"""

    object: str
    deleted: bool
    id: NotRequired[str]
    slug: NotRequired[str]
    external_id: NotRequired[str]


class DeletedObject(BaseModel):
    r"""Deleted Object"""

    object: str

    deleted: bool

    id: Optional[str] = None

    slug: Optional[str] = None

    external_id: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "slug", "external_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
