"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .schemas_enterpriseconnection import (
    SchemasEnterpriseConnection,
    SchemasEnterpriseConnectionTypedDict,
)
from clerk_backend_api.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class EnterpriseConnectionsTypedDict(TypedDict):
    r"""A list of enterprise connections"""

    data: List[SchemasEnterpriseConnectionTypedDict]
    total_count: int
    r"""Total number of enterprise connections"""


class EnterpriseConnections(BaseModel):
    r"""A list of enterprise connections"""

    data: List[SchemasEnterpriseConnection]

    total_count: int
    r"""Total number of enterprise connections"""
