"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .enterpriseconnectiontestrun import (
    EnterpriseConnectionTestRun,
    EnterpriseConnectionTestRunTypedDict,
)
from clerk_backend_api.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class EnterpriseConnectionTestRunsTypedDict(TypedDict):
    r"""A list of enterprise connection test runs"""

    data: List[EnterpriseConnectionTestRunTypedDict]
    total_count: int
    r"""Total number of test runs"""


class EnterpriseConnectionTestRuns(BaseModel):
    r"""A list of enterprise connection test runs"""

    data: List[EnterpriseConnectionTestRun]

    total_count: int
    r"""Total number of test runs"""
