"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clerk_backend_api.types import BaseModel, Nullable, UNSET_SENTINEL
from enum import Enum
from pydantic import model_serializer
from typing_extensions import TypedDict


class FeatureResponseObject(str, Enum):
    r"""String representing the object's type. Objects of the same type share the same value."""

    FEATURE = "feature"


class FeatureResponseTypedDict(TypedDict):
    object: FeatureResponseObject
    r"""String representing the object's type. Objects of the same type share the same value."""
    id: str
    r"""Unique identifier for the feature."""
    name: str
    r"""The name of the feature."""
    description: Nullable[str]
    r"""The description of the feature."""
    slug: str
    r"""The URL-friendly slug for the feature."""
    avatar_url: Nullable[str]
    r"""The URL of the feature's avatar image."""


class FeatureResponse(BaseModel):
    object: FeatureResponseObject
    r"""String representing the object's type. Objects of the same type share the same value."""

    id: str
    r"""Unique identifier for the feature."""

    name: str
    r"""The name of the feature."""

    description: Nullable[str]
    r"""The description of the feature."""

    slug: str
    r"""The URL-friendly slug for the feature."""

    avatar_url: Nullable[str]
    r"""The URL of the feature's avatar image."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = []
        nullable_fields = ["description", "avatar_url"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
