"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clerk_backend_api.models import ClerkBaseError
from clerk_backend_api.types import BaseModel
from clerk_backend_api.utils import FieldMetadata, PathParamMetadata
from dataclasses import dataclass, field
import httpx
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, TypedDict


class GetAPIKeySecretRequestTypedDict(TypedDict):
    api_key_id: str


class GetAPIKeySecretRequest(BaseModel):
    api_key_id: Annotated[
        str,
        pydantic.Field(alias="apiKeyID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]


class GetAPIKeySecretAPIKeysErrorsTypedDict(TypedDict):
    message: str
    long_message: str
    code: str


class GetAPIKeySecretAPIKeysErrors(BaseModel):
    message: str

    long_message: str

    code: str


class GetAPIKeySecretAPIKeysResponseResponseBodyData(BaseModel):
    errors: List[GetAPIKeySecretAPIKeysErrors]


@dataclass(unsafe_hash=True)
class GetAPIKeySecretAPIKeysResponseResponseBody(ClerkBaseError):
    r"""404 Not Found"""

    data: GetAPIKeySecretAPIKeysResponseResponseBodyData = field(hash=False)

    def __init__(
        self,
        data: GetAPIKeySecretAPIKeysResponseResponseBodyData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class GetAPIKeySecretErrorsTypedDict(TypedDict):
    message: str
    long_message: str
    code: str


class GetAPIKeySecretErrors(BaseModel):
    message: str

    long_message: str

    code: str


class GetAPIKeySecretAPIKeysResponseBodyData(BaseModel):
    errors: List[GetAPIKeySecretErrors]


@dataclass(unsafe_hash=True)
class GetAPIKeySecretAPIKeysResponseBody(ClerkBaseError):
    r"""400 Bad Request"""

    data: GetAPIKeySecretAPIKeysResponseBodyData = field(hash=False)

    def __init__(
        self,
        data: GetAPIKeySecretAPIKeysResponseBodyData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class GetAPIKeySecretResponseBodyTypedDict(TypedDict):
    r"""200 OK"""

    secret: str


class GetAPIKeySecretResponseBody(BaseModel):
    r"""200 OK"""

    secret: str
