"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clerk_backend_api import utils
from clerk_backend_api.types import BaseModel
from clerk_backend_api.utils import validate_open_enum
from enum import Enum
from pydantic.functional_validators import PlainValidator
from typing_extensions import Annotated, TypedDict


class Type(str, Enum, metaclass=utils.OpenEnumMeta):
    OAUTH_GOOGLE = "oauth_google"
    OAUTH_MOCK = "oauth_mock"
    SAML = "saml"
    OAUTH_MICROSOFT = "oauth_microsoft"
    EMAIL_LINK = "email_link"
    OAUTH_APPLE = "oauth_apple"
    OAUTH_DISCORD = "oauth_discord"
    OAUTH_GITHUB = "oauth_github"


class IdentificationLinkTypedDict(TypedDict):
    type: Type
    id: str


class IdentificationLink(BaseModel):
    type: Annotated[Type, PlainValidator(validate_open_enum(False))]

    id: str
