"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clerk_backend_api.types import BaseModel
from typing_extensions import TypedDict


class IdentificationLinkTypedDict(TypedDict):
    type: str
    id: str


class IdentificationLink(BaseModel):
    type: str

    id: str
