"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clerk_backend_api.types import BaseModel, Nullable, UNSET_SENTINEL
from enum import Enum
from pydantic import model_serializer
from typing import List
from typing_extensions import TypedDict


class InstanceObject(str, Enum):
    r"""String representing the object's type. Objects of the same type share the same value."""

    INSTANCE = "instance"


class InstanceTypedDict(TypedDict):
    r"""Success"""

    object: InstanceObject
    r"""String representing the object's type. Objects of the same type share the same value."""
    id: str
    environment_type: str
    allowed_origins: Nullable[List[str]]
    workspace_id: Nullable[str]
    r"""The ID of the Clerk workspace that owns the instance's application. It is null when the application has no owner."""


class Instance(BaseModel):
    r"""Success"""

    object: InstanceObject
    r"""String representing the object's type. Objects of the same type share the same value."""

    id: str

    environment_type: str

    allowed_origins: Nullable[List[str]]

    workspace_id: Nullable[str]
    r"""The ID of the Clerk workspace that owns the instance's application. It is null when the application has no owner."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
