"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clerk_backend_api.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from clerk_backend_api.utils import validate_const
from enum import Enum
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Any, Dict, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class InvitationRevokedObject(str, Enum):
    INVITATION = "invitation"


class InvitationRevokedStatus(str, Enum):
    REVOKED = "revoked"


class InvitationRevokedTypedDict(TypedDict):
    r"""Success"""

    object: InvitationRevokedObject
    id: str
    email_address: str
    public_metadata: Dict[str, Any]
    status: InvitationRevokedStatus
    created_at: int
    r"""Unix timestamp of creation.

    """
    updated_at: int
    r"""Unix timestamp of last update.

    """
    revoked: Literal[True]
    url: NotRequired[str]
    expires_at: NotRequired[Nullable[int]]
    r"""Unix timestamp of expiration.

    """


class InvitationRevoked(BaseModel):
    r"""Success"""

    object: InvitationRevokedObject

    id: str

    email_address: str

    public_metadata: Dict[str, Any]

    status: InvitationRevokedStatus

    created_at: int
    r"""Unix timestamp of creation.

    """

    updated_at: int
    r"""Unix timestamp of last update.

    """

    REVOKED: Annotated[
        Annotated[Optional[Literal[True]], AfterValidator(validate_const(True))],
        pydantic.Field(alias="revoked"),
    ] = True

    url: Optional[str] = None

    expires_at: OptionalNullable[int] = UNSET
    r"""Unix timestamp of expiration.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["revoked", "url", "expires_at"])
        nullable_fields = set(["expires_at"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    InvitationRevoked.model_rebuild()
except NameError:
    pass
