"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .machine import Machine, MachineTypedDict
from clerk_backend_api.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class MachineListTypedDict(TypedDict):
    r"""Success"""

    data: List[MachineTypedDict]
    total_count: int
    r"""Total number of machines"""


class MachineList(BaseModel):
    r"""Success"""

    data: List[Machine]

    total_count: int
    r"""Total number of machines"""
