"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clerk_backend_api.types import BaseModel
from datetime import datetime
from enum import Enum
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict


class ManagementUsageReportResponseObject(str, Enum):
    USAGE_REPORT = "usage_report"


class BillingCycleTypedDict(TypedDict):
    end: NotRequired[datetime]
    start: NotRequired[datetime]


class BillingCycle(BaseModel):
    end: Optional[datetime] = None

    start: Optional[datetime] = None


class ManagementUsageReportResponseTypedDict(TypedDict):
    object: ManagementUsageReportResponseObject
    billing_cycle: NotRequired[BillingCycleTypedDict]
    day_usage: NotRequired[Dict[str, Any]]
    cycle_usage: NotRequired[Dict[str, Any]]


class ManagementUsageReportResponse(BaseModel):
    object: ManagementUsageReportResponseObject

    billing_cycle: Optional[BillingCycle] = None

    day_usage: Optional[Dict[str, Any]] = None

    cycle_usage: Optional[Dict[str, Any]] = None
