"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clerk_backend_api.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import TypedDict


class OrganizationInvitationPublicUserDataTypedDict(TypedDict):
    r"""An organization inviter's public user data"""

    user_id: str
    first_name: Nullable[str]
    last_name: Nullable[str]
    image_url: str
    has_image: bool
    identifier: str


class OrganizationInvitationPublicUserData(BaseModel):
    r"""An organization inviter's public user data"""

    user_id: str

    first_name: Nullable[str]

    last_name: Nullable[str]

    image_url: str

    has_image: bool

    identifier: str

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
