"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .organizationmembershippublicuserdata import (
    OrganizationMembershipPublicUserData,
    OrganizationMembershipPublicUserDataTypedDict,
)
from clerk_backend_api.types import BaseModel, Nullable, UNSET_SENTINEL
from enum import Enum
from pydantic import model_serializer
from typing import Any, Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class OrganizationMembershipObject(str, Enum):
    r"""String representing the object's type. Objects of the same type share the same value."""

    ORGANIZATION_MEMBERSHIP = "organization_membership"


class OrganizationMembershipOrganizationObject(str, Enum):
    ORGANIZATION = "organization"


class OrganizationMembershipOrganizationTypedDict(TypedDict):
    object: OrganizationMembershipOrganizationObject
    id: str
    name: str
    slug: str
    has_image: bool
    max_allowed_memberships: int
    admin_delete_enabled: bool
    public_metadata: Dict[str, Any]
    created_at: int
    r"""Unix timestamp of creation.

    """
    updated_at: int
    r"""Unix timestamp of last update.

    """
    image_url: NotRequired[str]
    members_count: NotRequired[int]
    missing_member_with_elevated_permissions: NotRequired[bool]
    pending_invitations_count: NotRequired[int]
    private_metadata: NotRequired[Dict[str, Any]]
    created_by: NotRequired[str]
    last_active_at: NotRequired[int]
    r"""Unix timestamp of last activity.

    """


class OrganizationMembershipOrganization(BaseModel):
    object: OrganizationMembershipOrganizationObject

    id: str

    name: str

    slug: str

    has_image: bool

    max_allowed_memberships: int

    admin_delete_enabled: bool

    public_metadata: Dict[str, Any]

    created_at: int
    r"""Unix timestamp of creation.

    """

    updated_at: int
    r"""Unix timestamp of last update.

    """

    image_url: Optional[str] = None

    members_count: Optional[int] = None

    missing_member_with_elevated_permissions: Optional[bool] = None

    pending_invitations_count: Optional[int] = None

    private_metadata: Optional[Dict[str, Any]] = None

    created_by: Optional[str] = None

    last_active_at: Optional[int] = None
    r"""Unix timestamp of last activity.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "image_url",
                "members_count",
                "missing_member_with_elevated_permissions",
                "pending_invitations_count",
                "private_metadata",
                "created_by",
                "last_active_at",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class OrganizationMembershipTypedDict(TypedDict):
    r"""A user's membership in an organization"""

    id: str
    object: OrganizationMembershipObject
    r"""String representing the object's type. Objects of the same type share the same value.

    """
    role: str
    permissions: Nullable[List[str]]
    public_metadata: Dict[str, Any]
    r"""Metadata saved on the organization membership, accessible from both Frontend and Backend APIs"""
    organization: OrganizationMembershipOrganizationTypedDict
    created_at: int
    r"""Unix timestamp of creation."""
    updated_at: int
    r"""Unix timestamp of last update."""
    role_name: NotRequired[str]
    private_metadata: NotRequired[Dict[str, Any]]
    r"""Metadata saved on the organization membership, accessible only from the Backend API"""
    public_user_data: NotRequired[OrganizationMembershipPublicUserDataTypedDict]
    r"""An organization membership with public user data populated"""


class OrganizationMembership(BaseModel):
    r"""A user's membership in an organization"""

    id: str

    object: OrganizationMembershipObject
    r"""String representing the object's type. Objects of the same type share the same value.

    """

    role: str

    permissions: Nullable[List[str]]

    public_metadata: Dict[str, Any]
    r"""Metadata saved on the organization membership, accessible from both Frontend and Backend APIs"""

    organization: OrganizationMembershipOrganization

    created_at: int
    r"""Unix timestamp of creation."""

    updated_at: int
    r"""Unix timestamp of last update."""

    role_name: Optional[str] = None

    private_metadata: Optional[Dict[str, Any]] = None
    r"""Metadata saved on the organization membership, accessible only from the Backend API"""

    public_user_data: Optional[OrganizationMembershipPublicUserData] = None
    r"""An organization membership with public user data populated"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["role_name", "private_metadata", "public_user_data"])
        nullable_fields = set(["permissions"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
