"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clerk_backend_api.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, NotRequired, TypedDict


class OrganizationMembershipPublicUserDataTypedDict(TypedDict):
    r"""An organization membership with public user data populated"""

    user_id: str
    first_name: Nullable[str]
    last_name: Nullable[str]
    profile_image_url: Nullable[str]
    image_url: str
    has_image: bool
    identifier: NotRequired[Nullable[str]]
    username: NotRequired[Nullable[str]]


class OrganizationMembershipPublicUserData(BaseModel):
    r"""An organization membership with public user data populated"""

    user_id: str

    first_name: Nullable[str]

    last_name: Nullable[str]

    profile_image_url: Annotated[
        Nullable[str],
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible."
        ),
    ]

    image_url: str

    has_image: bool

    identifier: OptionalNullable[str] = UNSET

    username: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["identifier", "username"])
        nullable_fields = set(
            ["first_name", "last_name", "profile_image_url", "identifier", "username"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
