"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clerk_backend_api.types import BaseModel, UNSET_SENTINEL
from enum import Enum
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class Mode(str, Enum):
    r"""Controls the login_hint sent to the IdP on SSO sign-in"""

    EMAIL_ADDRESS = "email_address"
    CUSTOM_ATTRIBUTE = "custom_attribute"
    OFF = "off"


class SAMLConnectionLoginHintTypedDict(TypedDict):
    r"""Configuration for the login_hint sent to the IdP on SSO sign-in"""

    mode: Mode
    r"""Controls the login_hint sent to the IdP on SSO sign-in"""
    source: NotRequired[str]
    r"""The user public_metadata key whose value is sent as the login_hint when mode is custom_attribute"""


class SAMLConnectionLoginHint(BaseModel):
    r"""Configuration for the login_hint sent to the IdP on SSO sign-in"""

    mode: Mode
    r"""Controls the login_hint sent to the IdP on SSO sign-in"""

    source: Optional[str] = None
    r"""The user public_metadata key whose value is sent as the login_hint when mode is custom_attribute"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
