"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clerk_backend_api.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class SchemasEnterpriseConnectionSamlConnectionTypedDict(TypedDict):
    r"""Present when the enterprise connection uses SAML"""

    id: NotRequired[str]
    r"""SAML connection ID"""
    name: NotRequired[str]
    r"""SAML connection display name"""
    idp_entity_id: NotRequired[Nullable[str]]
    r"""IdP entity ID (optional, when connection details are loaded)"""
    idp_sso_url: NotRequired[Nullable[str]]
    r"""IdP SSO URL (optional, when connection details are loaded)"""
    idp_metadata_url: NotRequired[Nullable[str]]
    r"""IdP metadata URL (optional, when connection details are loaded)"""
    acs_url: NotRequired[Nullable[str]]
    r"""Assertion Consumer Service URL"""
    sp_entity_id: NotRequired[Nullable[str]]
    r"""Service Provider entity ID"""
    sp_metadata_url: NotRequired[Nullable[str]]
    r"""Service Provider metadata URL"""
    active: NotRequired[bool]
    r"""Whether the SAML connection is active"""
    allow_idp_initiated: NotRequired[bool]
    r"""Whether IdP-initiated SSO is allowed"""
    allow_subdomains: NotRequired[bool]
    r"""Whether subdomains are allowed for domain matching"""
    force_authn: NotRequired[bool]
    r"""Whether to force re-authentication"""


class SchemasEnterpriseConnectionSamlConnection(BaseModel):
    r"""Present when the enterprise connection uses SAML"""

    id: Optional[str] = None
    r"""SAML connection ID"""

    name: Optional[str] = None
    r"""SAML connection display name"""

    idp_entity_id: OptionalNullable[str] = UNSET
    r"""IdP entity ID (optional, when connection details are loaded)"""

    idp_sso_url: OptionalNullable[str] = UNSET
    r"""IdP SSO URL (optional, when connection details are loaded)"""

    idp_metadata_url: OptionalNullable[str] = UNSET
    r"""IdP metadata URL (optional, when connection details are loaded)"""

    acs_url: OptionalNullable[str] = UNSET
    r"""Assertion Consumer Service URL"""

    sp_entity_id: OptionalNullable[str] = UNSET
    r"""Service Provider entity ID"""

    sp_metadata_url: OptionalNullable[str] = UNSET
    r"""Service Provider metadata URL"""

    active: Optional[bool] = None
    r"""Whether the SAML connection is active"""

    allow_idp_initiated: Optional[bool] = None
    r"""Whether IdP-initiated SSO is allowed"""

    allow_subdomains: Optional[bool] = None
    r"""Whether subdomains are allowed for domain matching"""

    force_authn: Optional[bool] = None
    r"""Whether to force re-authentication"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "name",
                "idp_entity_id",
                "idp_sso_url",
                "idp_metadata_url",
                "acs_url",
                "sp_entity_id",
                "sp_metadata_url",
                "active",
                "allow_idp_initiated",
                "allow_subdomains",
                "force_authn",
            ]
        )
        nullable_fields = set(
            [
                "idp_entity_id",
                "idp_sso_url",
                "idp_metadata_url",
                "acs_url",
                "sp_entity_id",
                "sp_metadata_url",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class OauthConfigTypedDict(TypedDict):
    r"""Present when the enterprise connection uses OIDC"""

    id: NotRequired[str]
    r"""OAuth config ID"""
    name: NotRequired[str]
    r"""Custom OIDC provider display name"""
    provider_key: NotRequired[str]
    r"""OAuth provider key (e.g. oidc_custom)"""
    client_id: NotRequired[Nullable[str]]
    r"""OAuth client ID"""
    discovery_url: NotRequired[Nullable[str]]
    r"""OIDC discovery URL"""
    logo_public_url: NotRequired[Nullable[str]]
    r"""Logo URL for the provider"""
    created_at: NotRequired[int]
    r"""Unix timestamp in milliseconds when the config was created"""
    updated_at: NotRequired[int]
    r"""Unix timestamp in milliseconds when the config was last updated"""


class OauthConfig(BaseModel):
    r"""Present when the enterprise connection uses OIDC"""

    id: Optional[str] = None
    r"""OAuth config ID"""

    name: Optional[str] = None
    r"""Custom OIDC provider display name"""

    provider_key: Optional[str] = None
    r"""OAuth provider key (e.g. oidc_custom)"""

    client_id: OptionalNullable[str] = UNSET
    r"""OAuth client ID"""

    discovery_url: OptionalNullable[str] = UNSET
    r"""OIDC discovery URL"""

    logo_public_url: OptionalNullable[str] = UNSET
    r"""Logo URL for the provider"""

    created_at: Optional[int] = None
    r"""Unix timestamp in milliseconds when the config was created"""

    updated_at: Optional[int] = None
    r"""Unix timestamp in milliseconds when the config was last updated"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "name",
                "provider_key",
                "client_id",
                "discovery_url",
                "logo_public_url",
                "created_at",
                "updated_at",
            ]
        )
        nullable_fields = set(["client_id", "discovery_url", "logo_public_url"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class SchemasEnterpriseConnectionTypedDict(TypedDict):
    id: str
    r"""The enterprise connection ID"""
    name: str
    r"""The display name of the connection"""
    active: bool
    r"""Whether the enterprise connection is active"""
    domains: List[str]
    r"""Domains associated with the enterprise connection"""
    created_at: int
    r"""Unix timestamp in milliseconds when the connection was created"""
    updated_at: int
    r"""Unix timestamp in milliseconds when the connection was last updated"""
    organization_id: NotRequired[Nullable[str]]
    r"""Organization ID when the connection is linked to an organization"""
    sync_user_attributes: NotRequired[bool]
    r"""Controls whether to update the user's attributes on each sign-in"""
    disable_additional_identifications: NotRequired[bool]
    r"""When true, users cannot add additional identifications when using this connection"""
    saml_connection: NotRequired[
        Nullable[SchemasEnterpriseConnectionSamlConnectionTypedDict]
    ]
    r"""Present when the enterprise connection uses SAML"""
    oauth_config: NotRequired[Nullable[OauthConfigTypedDict]]
    r"""Present when the enterprise connection uses OIDC"""


class SchemasEnterpriseConnection(BaseModel):
    id: str
    r"""The enterprise connection ID"""

    name: str
    r"""The display name of the connection"""

    active: bool
    r"""Whether the enterprise connection is active"""

    domains: List[str]
    r"""Domains associated with the enterprise connection"""

    created_at: int
    r"""Unix timestamp in milliseconds when the connection was created"""

    updated_at: int
    r"""Unix timestamp in milliseconds when the connection was last updated"""

    organization_id: OptionalNullable[str] = UNSET
    r"""Organization ID when the connection is linked to an organization"""

    sync_user_attributes: Optional[bool] = None
    r"""Controls whether to update the user's attributes on each sign-in"""

    disable_additional_identifications: Optional[bool] = None
    r"""When true, users cannot add additional identifications when using this connection"""

    saml_connection: OptionalNullable[SchemasEnterpriseConnectionSamlConnection] = UNSET
    r"""Present when the enterprise connection uses SAML"""

    oauth_config: OptionalNullable[OauthConfig] = UNSET
    r"""Present when the enterprise connection uses OIDC"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "organization_id",
                "sync_user_attributes",
                "disable_additional_identifications",
                "saml_connection",
                "oauth_config",
            ]
        )
        nullable_fields = set(["organization_id", "saml_connection", "oauth_config"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
