"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from clerk_backend_api.types import BaseModel
from typing import TypedDict


class SvixURLTypedDict(TypedDict):
    svix_url: str
    

class SvixURL(BaseModel):
    svix_url: str
    
