"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clerk_backend_api.types import BaseModel
from enum import Enum
from typing_extensions import TypedDict


class TokenObject(str, Enum):
    r"""String representing the object's type. Objects of the same type share the same value."""

    TOKEN = "token"


class TokenTypedDict(TypedDict):
    object: TokenObject
    r"""String representing the object's type. Objects of the same type share the same value.

    """
    jwt: str
    r"""String representing the encoded jwt value.

    """


class Token(BaseModel):
    object: TokenObject
    r"""String representing the object's type. Objects of the same type share the same value.

    """

    jwt: str
    r"""String representing the encoded jwt value.

    """
