"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clerk_backend_api.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class UpdateInstanceOrganizationSettingsRequestBodyTypedDict(TypedDict):
    enabled: NotRequired[Nullable[bool]]
    max_allowed_memberships: NotRequired[Nullable[int]]
    admin_delete_enabled: NotRequired[Nullable[bool]]
    domains_enabled: NotRequired[Nullable[bool]]
    slug_disabled: NotRequired[Nullable[bool]]
    domains_enrollment_modes: NotRequired[List[str]]
    r"""Specify which enrollment modes to enable for your Organization Domains.
    Supported modes are 'automatic_invitation' & 'automatic_suggestion'.
    """
    creator_role_id: NotRequired[Nullable[str]]
    r"""Specify what the default organization role is for an organization creator."""
    domains_default_role_id: NotRequired[Nullable[str]]
    r"""Specify what the default organization role is for the organization domains."""


class UpdateInstanceOrganizationSettingsRequestBody(BaseModel):
    enabled: OptionalNullable[bool] = UNSET

    max_allowed_memberships: OptionalNullable[int] = UNSET

    admin_delete_enabled: OptionalNullable[bool] = UNSET

    domains_enabled: OptionalNullable[bool] = UNSET

    slug_disabled: OptionalNullable[bool] = UNSET

    domains_enrollment_modes: Optional[List[str]] = None
    r"""Specify which enrollment modes to enable for your Organization Domains.
    Supported modes are 'automatic_invitation' & 'automatic_suggestion'.
    """

    creator_role_id: OptionalNullable[str] = UNSET
    r"""Specify what the default organization role is for an organization creator."""

    domains_default_role_id: OptionalNullable[str] = UNSET
    r"""Specify what the default organization role is for the organization domains."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "enabled",
                "max_allowed_memberships",
                "admin_delete_enabled",
                "domains_enabled",
                "slug_disabled",
                "domains_enrollment_modes",
                "creator_role_id",
                "domains_default_role_id",
            ]
        )
        nullable_fields = set(
            [
                "enabled",
                "max_allowed_memberships",
                "admin_delete_enabled",
                "domains_enabled",
                "slug_disabled",
                "creator_role_id",
                "domains_default_role_id",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
