"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clerk_backend_api.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from clerk_backend_api.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateJWTTemplateClaimsTypedDict(TypedDict):
    r"""JWT template claims in JSON format"""


class UpdateJWTTemplateClaims(BaseModel):
    r"""JWT template claims in JSON format"""


class UpdateJWTTemplateRequestBodyTypedDict(TypedDict):
    name: str
    r"""JWT template name"""
    claims: UpdateJWTTemplateClaimsTypedDict
    r"""JWT template claims in JSON format"""
    lifetime: NotRequired[Nullable[int]]
    r"""JWT lifetime"""
    allowed_clock_skew: NotRequired[Nullable[int]]
    r"""JWT allowed clock skew"""
    custom_signing_key: NotRequired[bool]
    r"""Whether a custom signing key/algorithm is also provided for this template"""
    signing_algorithm: NotRequired[Nullable[str]]
    r"""The custom signing algorithm to use when minting JWTs. Required if `custom_signing_key` is `true`."""
    signing_key: NotRequired[Nullable[str]]
    r"""The custom signing private key to use when minting JWTs. Required if `custom_signing_key` is `true`."""


class UpdateJWTTemplateRequestBody(BaseModel):
    name: str
    r"""JWT template name"""

    claims: UpdateJWTTemplateClaims
    r"""JWT template claims in JSON format"""

    lifetime: OptionalNullable[int] = UNSET
    r"""JWT lifetime"""

    allowed_clock_skew: OptionalNullable[int] = UNSET
    r"""JWT allowed clock skew"""

    custom_signing_key: Optional[bool] = None
    r"""Whether a custom signing key/algorithm is also provided for this template"""

    signing_algorithm: OptionalNullable[str] = UNSET
    r"""The custom signing algorithm to use when minting JWTs. Required if `custom_signing_key` is `true`."""

    signing_key: OptionalNullable[str] = UNSET
    r"""The custom signing private key to use when minting JWTs. Required if `custom_signing_key` is `true`."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "lifetime",
                "allowed_clock_skew",
                "custom_signing_key",
                "signing_algorithm",
                "signing_key",
            ]
        )
        nullable_fields = set(
            ["lifetime", "allowed_clock_skew", "signing_algorithm", "signing_key"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UpdateJWTTemplateRequestTypedDict(TypedDict):
    template_id: str
    r"""The ID of the JWT template to update"""
    request_body: NotRequired[UpdateJWTTemplateRequestBodyTypedDict]


class UpdateJWTTemplateRequest(BaseModel):
    template_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the JWT template to update"""

    request_body: Annotated[
        Optional[UpdateJWTTemplateRequestBody],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["RequestBody"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
