"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clerk_backend_api.types import BaseModel
from clerk_backend_api.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class UserPasskeyDeleteRequestTypedDict(TypedDict):
    user_id: str
    r"""The ID of the user that owns the passkey identity"""
    passkey_identification_id: str
    r"""The ID of the passkey identity to be deleted"""


class UserPasskeyDeleteRequest(BaseModel):
    user_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the user that owns the passkey identity"""

    passkey_identification_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the passkey identity to be deleted"""
