"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from clerk_backend_api.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class KeysTypedDict(TypedDict):
    use: NotRequired[str]
    kty: NotRequired[str]
    kid: NotRequired[str]
    alg: NotRequired[str]
    n: NotRequired[str]
    e: NotRequired[str]


class Keys(BaseModel):
    use: Optional[str] = None

    kty: Optional[str] = None

    kid: Optional[str] = None

    alg: Optional[str] = None

    n: Optional[str] = None

    e: Optional[str] = None


class WellKnownJWKSTypedDict(TypedDict):
    r"""Get the JSON Web Key Set"""

    keys: NotRequired[List[KeysTypedDict]]


class WellKnownJWKS(BaseModel):
    r"""Get the JSON Web Key Set"""

    keys: Optional[List[Keys]] = None
